import { Property } from '../types';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'a1111111-1111-1111-1111-111111111111',
    title: 'Palm Meadows Villa',
    address: 'Whitefield Main Road, Bengaluru, KA',
    city: 'Bengaluru',
    state: 'KA',
    price: 65000,
    period: 'month',
    beds: 3,
    baths: 3,
    dimensions: '1,850 sq.ft',
    image_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    images: [
      { r2_url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80', is_primary: true, display_order: 0, caption: 'Living Pavilion with High Ceilings' },
      { r2_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', is_primary: false, display_order: 1, caption: 'Quiet Courtyard & Private Garden' },
      { r2_url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80', is_primary: false, display_order: 2, caption: 'Acoustic-Isolated Study Room' }
    ],
    is_popular: true,
    category: 'rent',
    property_type: 'Luxury Villa',
    description: 'Immaculately maintained 3 BHK gated villa situated 12 minutes from Manipal Hospital Whitefield. Tailored for senior consultants with an acoustic-isolated study room, triple-track blackout drapery for rotating shifts, and 100% automatic diesel generator power backup.',
    hospital_name: 'Manipal Hospital Whitefield',
    hospital_distance: '1.8 km to Manipal Hospital Whitefield',
    commute_estimate: 'Approx. 12 min drive at 8:00 AM',
    verified_date: '14 September 2026',
    verification_method: 'Physical On-Site Inspection & Lease Title Verified',
    furnishing: 'Semi-Furnished',
    deposit: 300000,
    maintenance: 4500,
    workday_amenities: [
      '100% DG Power Backup',
      'Acoustic-Isolated Doctor Study',
      'Blackout Bedroom Drapery',
      'Covered Dedicated Parking (2 Cars)',
      '24/7 Gated Security & Rapid Exit',
      'Shift-Friendly Concierge Viewing'
    ],
    floor: 'Independent G+1',
    facing: 'East Facing',
    owner_email: 'doctor.demo@medproperties.com',
    status: 'active'
  },
  {
    id: 'a2222222-2222-2222-2222-222222222222',
    title: 'Jubilee Enclave Villa',
    address: 'Road No. 36, Jubilee Hills, Hyderabad, TS',
    city: 'Hyderabad',
    state: 'TS',
    price: 85000,
    period: 'month',
    beds: 4,
    baths: 4,
    dimensions: '2,400 sq.ft',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    images: [
      { r2_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', is_primary: true, display_order: 0, caption: 'Architectural Facade & Private Portico' },
      { r2_url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80', is_primary: false, display_order: 1, caption: 'Master Suite with Blackout Shading' },
      { r2_url: 'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80', is_primary: false, display_order: 2, caption: 'Chef Kitchen with Piped Gas' }
    ],
    is_popular: true,
    category: 'rent',
    property_type: 'Executive Villa',
    description: 'Refined 4 BHK executive residence in prime Jubilee Hills, located 8 minutes from Apollo Health City. Features expansive master suite, dedicated medical reading desk, EV vehicle charger, dual water source, and quiet residential neighborhood.',
    hospital_name: 'Apollo Hospitals Jubilee Hills',
    hospital_distance: '2.1 km to Apollo Hospitals Jubilee Hills',
    commute_estimate: 'Approx. 8 min drive at 8:00 AM',
    verified_date: '22 September 2026',
    verification_method: 'Structural & Title Audit Verified by Legal Counsel',
    furnishing: 'Fully Furnished',
    deposit: 400000,
    maintenance: 6000,
    workday_amenities: [
      '100% DG Power Backup',
      'EV Charging Station Installed',
      'High-Speed Fiber Dual ISP',
      'Private Terrace Garden',
      '24/7 Monitored Access Control'
    ],
    floor: 'Independent 2-Level Villa',
    facing: 'North-East Facing',
    owner_email: 'doctor.demo@medproperties.com',
    status: 'active'
  },
  {
    id: 'a3333333-3333-3333-3333-333333333333',
    title: 'Worli Sea Face Specialist Suite',
    address: 'Khan Abdul Gaffar Khan Marg, Worli, Mumbai, MH',
    city: 'Mumbai',
    state: 'MH',
    price: 145000,
    period: 'month',
    beds: 3,
    baths: 3,
    dimensions: '1,700 sq.ft',
    image_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
    images: [
      { r2_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80', is_primary: true, display_order: 0, caption: 'Panoramic Arabian Sea View' },
      { r2_url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80', is_primary: false, display_order: 1, caption: 'Quiet Sunset Balcony' }
    ],
    is_popular: true,
    category: 'rent',
    property_type: 'Sea View Apartment',
    description: 'High-floor sea-facing apartment offering deep calm and restorative rest for department heads and surgeons. Fast Bandra-Worli Sea Link connection provides seamless 18-minute transit to Lilavati Hospital Bandra.',
    hospital_name: 'Lilavati Hospital & Research Centre',
    hospital_distance: '3.2 km to Lilavati Hospital Bandra via Sea Link',
    commute_estimate: 'Approx. 18 min via Sea Link at 8:00 AM',
    verified_date: '18 September 2026',
    verification_method: 'On-Site Decibel Noise Audit & Registered Society NOC',
    furnishing: 'Fully Furnished',
    deposit: 600000,
    maintenance: 12000,
    workday_amenities: [
      'Double-Glazed Acoustic Glazing',
      'Direct Bandra-Worli Sea Link Ramp',
      'Dual High-Speed Elevators',
      'Reserved Podium Parking',
      'Concierge Parcel & Key Management'
    ],
    floor: '18th Floor of 24',
    facing: 'West (Sea Facing)',
    status: 'active'
  },
  {
    id: 'a4444444-4444-4444-4444-444444444444',
    title: 'Saket Greens Contemporary Residence',
    address: 'Press Enclave Road, Saket, New Delhi, DL',
    city: 'Delhi NCR',
    state: 'DL',
    price: 72000,
    period: 'month',
    beds: 3,
    baths: 3,
    dimensions: '1,950 sq.ft',
    image_url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    is_popular: false,
    category: 'rent',
    property_type: 'Contemporary Floor',
    description: 'Spacious 3 BHK builder floor situated directly opposite Max Super Speciality Hospital Saket, and 16 minutes from AIIMS New Delhi. Private balcony garden, Italian marble flooring, and modular pantry.',
    hospital_name: 'Max Super Speciality Hospital Saket',
    hospital_distance: '1.1 km to Max Super Speciality Hospital Saket',
    commute_estimate: 'Approx. 5 min drive / 12 min walk',
    verified_date: '10 September 2026',
    verification_method: 'Physical Inspection & Land Title Registry Verification',
    furnishing: 'Semi-Furnished',
    deposit: 200000,
    maintenance: 3000,
    workday_amenities: [
      '100% Inverter & DG Power Backup',
      'Elevator Direct to Floor',
      'Sound-Insulated Master Bedroom',
      'Covered Stilt Parking Slot',
      'Walking Distance to Max Hospital'
    ],
    floor: '2nd Floor of 4',
    facing: 'North-East Facing',
    status: 'active'
  },
  {
    id: 'a5555555-5555-5555-5555-555555555555',
    title: 'Koramangala Medical Suites',
    address: '80 Feet Road, 4th Block Koramangala, Bengaluru, KA',
    city: 'Bengaluru',
    state: 'KA',
    price: 38000,
    period: 'month',
    beds: 2,
    baths: 2,
    dimensions: '1,150 sq.ft',
    image_url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    is_popular: false,
    category: 'rent',
    property_type: 'Furnished Apartment',
    description: 'Turnkey fully-furnished 2 BHK apartment designed for fellows, residents, and visiting medical faculty. 900 meters from St. John’s Medical College Hospital with high-speed Wi-Fi and weekly housekeeping option.',
    hospital_name: 'St. John’s Medical College Hospital',
    hospital_distance: '900 meters to St. John’s Hospital',
    commute_estimate: 'Approx. 4 min drive / 10 min walk',
    verified_date: '19 September 2026',
    verification_method: 'Verified Clean Lease & Verified Landlord Agreement',
    furnishing: 'Fully Furnished',
    deposit: 150000,
    maintenance: 2500,
    workday_amenities: [
      'Dedicated Workstation with Dual Monitors',
      'High-Speed 300 Mbps Fiber Internet',
      'Blackout Room Curtains',
      'Covered Scooter & Car Parking',
      'Water Purifier & Washing Machine'
    ],
    floor: '3rd Floor of 5',
    facing: 'North Facing',
    status: 'active'
  },
  {
    id: 'a6666666-6666-6666-6666-666666666666',
    title: 'Anna Nagar Heritage Residence',
    address: '2nd Avenue, Anna Nagar, Chennai, TN',
    city: 'Chennai',
    state: 'TN',
    price: 48000,
    period: 'month',
    beds: 3,
    baths: 2,
    dimensions: '1,600 sq.ft',
    image_url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80',
    is_popular: false,
    category: 'rent',
    property_type: 'Heritage Villa',
    description: 'Serene tree-lined residential home with private shaded courtyard garden. Convenient 12-minute commute to MGM Healthcare, Apollo Hospitals Greams Road, and Madras Medical College.',
    hospital_name: 'MGM Healthcare & Apollo Hospitals',
    hospital_distance: '2.4 km to MGM Healthcare Chennai',
    commute_estimate: 'Approx. 12 min drive at 8:00 AM',
    verified_date: '20 September 2026',
    verification_method: 'Physical On-Site Lease & Water Potability Audit',
    furnishing: 'Semi-Furnished',
    deposit: 240000,
    maintenance: 2000,
    workday_amenities: [
      'Private Tree-Lined Garden',
      '100% Inverter Backup System',
      'Dual Borewell and Corporation Water',
      'Covered Garage',
      'Quiet Residential Zone'
    ],
    floor: 'Ground Floor Independent',
    facing: 'South-East Facing',
    status: 'active'
  },
  // Properties for BUY (Luxury Doctor Residences for Acquisition)
  {
    id: 'b1111111-1111-1111-1111-111111111111',
    title: 'Indiranagar Prestige Doctor Residence',
    address: '100 Feet Road, Indiranagar, Bengaluru, KA',
    city: 'Bengaluru',
    state: 'KA',
    price: 34000000, // ₹3.40 Cr
    period: 'total',
    beds: 3,
    baths: 3,
    dimensions: '2,400 sq.ft',
    image_url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
    images: [
      { r2_url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80', is_primary: true, display_order: 0, caption: 'Modernist Architecture & Glass Balconies' },
      { r2_url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80', is_primary: false, display_order: 1, caption: 'Private Consultation Library' }
    ],
    is_popular: true,
    category: 'buy',
    property_type: 'Luxury Condominium',
    description: 'Exclusive 3 BHK plus library residence situated 8 minutes from Manipal Hospital (HAL). Features A-Khata clear title, RERA certification, acoustic floor isolation, private basement parking, and clubhouse amenities.',
    hospital_name: 'Manipal Hospital HAL Old Airport Rd',
    hospital_distance: '2.0 km to Manipal Hospital HAL',
    commute_estimate: 'Approx. 8 min drive at 8:00 AM',
    verified_date: '02 September 2026',
    verification_method: 'A-Khata Title Verified & Encumbrance Certificate Clean',
    furnishing: 'Fully Furnished',
    deposit: 0,
    maintenance: 8500,
    workday_amenities: [
      'A-Khata Clear Freehold Title',
      'Doctor Consultation Home Office',
      'EV Supercharger in Basement',
      '100% Generator Backup 24/7',
      'Pre-Approved for Medical Professional Home Loans'
    ],
    floor: '5th Floor of 12',
    facing: 'East Facing',
    status: 'active'
  },
  {
    id: 'b2222222-2222-2222-2222-222222222222',
    title: 'Golf Course Extension Doctors Haven',
    address: 'Sector 65, Golf Course Extension Rd, Gurugram, HR',
    city: 'Delhi NCR',
    state: 'HR',
    price: 27500000, // ₹2.75 Cr
    period: 'total',
    beds: 4,
    baths: 4,
    dimensions: '2,650 sq.ft',
    image_url: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
    is_popular: true,
    category: 'buy',
    property_type: 'High-Rise Penthouse',
    description: 'Ultra-modern 4 BHK penthouse with wraparound deck offering unhindered green views. Located 14 minutes from Fortis Memorial Research Institute and Medanta The Medicity, with doctor home-loan subsidies pre-evaluated.',
    hospital_name: 'Fortis Memorial Research Institute & Medanta',
    hospital_distance: '4.8 km to Fortis Gurugram',
    commute_estimate: 'Approx. 14 min drive via SPR',
    verified_date: '08 September 2026',
    verification_method: 'RERA Certified & Occupancy Certificate Received',
    furnishing: 'Semi-Furnished',
    deposit: 0,
    maintenance: 9200,
    workday_amenities: [
      'Central Air Conditioning with HEPA Filtration',
      'Soundproof Triple-Glazed Facade',
      'High-Speed Elevators with Power Backup',
      'Dedicated Basement Stalls (2)',
      'Bank Loan Pre-Sanction Support'
    ],
    floor: '22nd Floor Penthouse',
    facing: 'North-East Facing',
    status: 'active'
  },
  {
    id: 'b3333333-3333-3333-3333-333333333333',
    title: 'Bandra West Specialist Penthouse',
    address: 'Pali Hill, Bandra West, Mumbai, MH',
    city: 'Mumbai',
    state: 'MH',
    price: 58000000, // ₹5.80 Cr
    period: 'total',
    beds: 4,
    baths: 4,
    dimensions: '2,900 sq.ft',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    is_popular: false,
    category: 'buy',
    property_type: 'Duplex Penthouse',
    description: 'Premier duplex residence atop peaceful Pali Hill. Just 6 minutes from Lilavati Hospital and Hinduja Healthcare. Features private rooftop terrace, dedicated elevator lobby, and concierge security.',
    hospital_name: 'Lilavati Hospital Bandra',
    hospital_distance: '1.4 km to Lilavati Hospital',
    commute_estimate: 'Approx. 6 min drive / 15 min walk',
    verified_date: '16 September 2026',
    verification_method: 'Clear Co-op Society Title & Occupancy Certificate Verified',
    furnishing: 'Fully Furnished',
    deposit: 0,
    maintenance: 18000,
    workday_amenities: [
      'Private Elevator Access to Penthouse',
      'Full Home Soundproofing & Double Glazing',
      '100% Diesel Generator Continuous Backup',
      'Valet Parking & Secured Car Port (3 Slots)',
      'Doctor Relocation Mortgage Advisory'
    ],
    floor: 'Duplex 11th & 12th Floor',
    facing: 'Sea Breeze West',
    status: 'active'
  }
];

export const TESTIMONIALS = [
  {
    id: '1',
    quote: "MedProperties understood exactly what my family needed during my pediatric residency transition to AIIMS New Delhi. Their verified commute calculations and shift-friendly evening viewings saved us weeks of wasted travel.",
    author: 'Dr. Rajesh Sharma, MD',
    role: 'Chief Pediatric Resident',
    hospital: 'AIIMS New Delhi',
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: '2',
    quote: "As a consultant orthopedic surgeon on emergency trauma calls in Bengaluru, having a guaranteed 12-minute commute to Manipal Hospital was non-negotiable. MedProperties delivered a verified, quiet home within 48 hours.",
    author: 'Dr. Priya Nair, MS',
    role: 'Consultant Orthopedic Surgeon',
    hospital: 'Manipal Hospital Bengaluru',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=300&q=80'
  },
  {
    id: '3',
    quote: "Listing my apartment on MedProperties connected me with verified physician tenants who respect the property. Transparent lease execution, prompt deposit escrow, and zero tenant friction have made this seamless.",
    author: 'Ananya Deshmukh',
    role: 'Property Owner & Healthcare Landlord',
    hospital: 'Apollo Hospitals Medical District, Hyderabad',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80'
  }
];

export const VERIFIED_HOSPITAL_HUBS = [
  { name: 'Manipal Hospital (HAL Old Airport Rd)', city: 'Bengaluru', locality: 'HAL / Indiranagar' },
  { name: 'Manipal Hospital Whitefield', city: 'Bengaluru', locality: 'Whitefield' },
  { name: 'AIIMS New Delhi', city: 'Delhi NCR', locality: 'Ansari Nagar' },
  { name: 'Max Super Speciality Hospital Saket', city: 'Delhi NCR', locality: 'Saket' },
  { name: 'Fortis Memorial Research Institute', city: 'Delhi NCR', locality: 'Sector 44, Gurugram' },
  { name: 'Apollo Hospitals Jubilee Hills', city: 'Hyderabad', locality: 'Jubilee Hills' },
  { name: 'Lilavati Hospital & Research Centre', city: 'Mumbai', locality: 'Bandra West' },
  { name: 'Tata Memorial Hospital', city: 'Mumbai', locality: 'Parel' },
  { name: 'MGM Healthcare & Apollo Hospitals', city: 'Chennai', locality: 'Aminjikarai / Greams Rd' },
  { name: 'Jehangir Hospital & Ruby Hall Clinic', city: 'Pune', locality: 'Sassoon Rd / Bund Garden' },
];
